name: Java Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Build Setup
        run: ./mvnw -B -V clean install --no-transfer-progress
      - name: Integration Test with Maven
        run: ./mvnw -B -V -DtestSrc=remote -Prun-its clean install -Dinvoker.parallelThreads=4 --no-transfer-progress
